---
title: "Single Cell SIMLR attempt"
author: "Maximilian Lombardo"
date: "February 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(SIMLR)
```


```{r}
single.cell.data <- read.table("C:/Thesis/data/RegevSingleCell/GSE57872_GBM_data_matrix.txt", sep = '\t',
                               header = TRUE, row.names = 1)

est.num.clusters <- SIMLR_Estimate_Number_of_Clusters(single.cell.data, NUMC = 2:10)

c1 <- which.min(est.num.clusters$K1)
c2 <- which.min(est.num.clusters$K2)

c <- c(c1, c2)[which.min(c(c1, c2))]

simlr.result <- SIMLR(single.cell.data, c = 4, k= 75, no.dim = 500, normalize = FALSE)


displayClustersWithHeatmap(simlr.result$S*10, simlr.result$y$cluster)


feature.ranking.result <- SIMLR_Feature_Ranking(A = simlr.result$S, single.cell.data)

ranked.genes <- rownames(single.cell.data)[feature.ranking.result$aggR]
pval <- feature.ranking.result$pval
bonferroni.cutoff <- 0.05/length(ranked.genes)
significant.ranked.genes <- ranked.genes[pval <= bonferroni.cutoff]


significant.feature.expression <- single.cell.data[rev(significant.ranked.genes),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(significant.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])
```


```{r}
###Looking at gene sets for the glioblastoma multiforme subtypes

mesenchymal <- read.table("C:/Thesis/data/RegevSingleCell/genesets/VERHAAK_GLIOBLASTOMA_MESENCHYMAL.gmt", sep = "\t", stringsAsFactors = FALSE)
mesenchymal <- as.character(mesenchymal[1,])[c(-1,-2)]

proneural <- read.table("C:/Thesis/data/RegevSingleCell/genesets/VERHAAK_GLIOBLASTOMA_PRONEURAL.gmt", sep = "\t", stringsAsFactors = FALSE)
proneural <- as.character(proneural[1,])[c(-1,-2)]


neural <- read.table("C:/Thesis/data/RegevSingleCell/genesets/VERHAAK_GLIOBLASTOMA_NEURAL.gmt", sep = "\t", stringsAsFactors = FALSE)
neural <- as.character(neural[1,])[c(-1,-2)]

classical <- read.table("C:/Thesis/data/RegevSingleCell/genesets/VERHAAK_GLIOBLASTOMA_CLASSICAL.gmt", sep = "\t", stringsAsFactors = FALSE)
classical <- as.character(classical[1,])[c(-1,-2)]

```

```{r}
###Heatmap view of expression -- redo clustering?

#neural
neural.feature.expression <- single.cell.data[intersect(neural, rownames(single.cell.data)),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(neural.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])

#proneural
proneural.feature.expression <- single.cell.data[intersect(proneural, rownames(single.cell.data)),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(proneural.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])

#mesenchymal
mesenchymal.feature.expression <- single.cell.data[intersect(mesenchymal, rownames(single.cell.data)),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(mesenchymal.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])

#classical
classical.feature.expression <- single.cell.data[intersect(classical, rownames(single.cell.data)),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(classical.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])

#TEST
classical.feature.expression <- single.cell.data[intersect(proneural, significant.ranked.genes),rev(order(simlr.result$y$cluster))]

heatmap(as.matrix(classical.feature.expression), Rowv = NA, Colv = NA, labCol = simlr.result$y$cluster[rev(order(simlr.result$y$cluster))])


```

