---
title: "makePlots"
author: "Maximilian Lombardo"
date: "August 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Making figures using simulated data
#Make sure to have local version of SNFTool installed
#Load utility functions
util.fxns <- "~/Documents/uva/master/the/utils/simMVData.R" 
#util.fxns <- "~/Documents/gitRepos/master/utils/simMVData.R"
source(util.fxns)

snf.fxns <- "~/Documents/uva/master/the/utils/snf_fxns.R"
#snf.fxns <- "~/Documents/gitRepos/master/utils/snf_fxns.R"
source(snf.fxns)

#Source mkkm functions
mkm.fxns <- "~/Documents/uva/master/the/utils/mkkm_fxns.R"


plotting.fxns <- "~/Documents/uva/master/the/utils/plotting_fxns.R"
#plotting.fxns <- "~/Documents/gitRepos/master/utils/plotting_fxns.R"
source(plotting.fxns)

###Clean up this particular set of functions, redundant
#exp.plot.fxns <- "~/Documents/gitRepos/master/utils/simulatedExploratoryPlots.R"
#source(exp.plot.fxns)
```

```{r}
#Load Simulated Data from Similarity Network Fusion
library(SNFtool)



#Data and Labels for simulated scenario B
noise.sim <- simulateNoisyData(gaussian.noise = 3, gamma.noise = 4)

#Data and labels for simulated Scenario C
#misclass.sim <- simulateMisclassificationData(num = 1000, rad = 2.2)
perturb.sim <- simulatePerturbationData(num = 1000, pct.switch = 0.2)
```


```{r}
#Chapter 4 Figures
#Figure 1 Individual Simulated Data Scatter Views

#Add more types of noise to this figure and get rid of second portion?
#Scenario B Gaussian and Gamma Noise added to ground truth
plotSimDataScatter(dat = noise.sim$ground.truth[,c("V1", "V2")],
                   lab = noise.sim$ground.truth[,c("label")],
                   main.title =  "Noisy Simulated Data Ground Truth")
plotSimDataScatter(dat = noise.sim$gaussian.noise[,c("V1", "V2")],
                   lab = noise.sim$gaussian.noise[,c("label")],
                   main.title =  "Noisy Simulated Data Gaussian Noise")
plotSimDataScatter(dat = noise.sim$gamma.noise[,c("V1", "V2")],
                   lab = noise.sim$gamma.noise[,c("label")],
                   main.title =  "Noisy Simulated Data Gamma Noise")

# Scenario C Misclassification on the Boundaries of Groups
plotSimDataScatter(dat = perturb.sim$ground.truth[,c("V1", "V2")],
                   lab = perturb.sim$ground.truth[,c("label")],
                   main.title =  "Perturbation Simulation Ground Truth")
plotSimDataScatter(dat = perturb.sim$perturbation.1[,c("V1", "V2")],
                   lab = perturb.sim$perturbation.1[,c("label")],
                   main.title =  "Perturbation Simulation Scenario 1")
plotSimDataScatter(dat = perturb.sim$perturbation.2[,c("V1", "V2")],
                   lab = perturb.sim$perturbation.2[,c("label")],
                   main.title =  "Perturbation Simulation Scenario 2")

```



```{r}
#Chapter 4 Figures
#Figure 2 Similarity Network Fusion Heat Comparison
#Scenario A - inverted labels

#Scenario B - Noisy views
snf.b <- runSNFPipeline(Data1 = noise.sim$gaussian.noise,
                        Data2 = noise.sim$gamma.noise,
                        truelabel = noise.sim$true.label,
                        alpha = 1, down.pct = 0.2)
b.nmi <- plotSNFHeatComparison(all.data = snf.b$affinity.matrices,
                               truelabel = noise.sim$true.label,
                               down.pct = 0.2)
#Scenario C - perturbation
snf.c <- runSNFPipeline(Data1 = perturb.sim$perturbation.1,
                        Data2 = perturb.sim$perturbation.2,
                        truelabel = perturb.sim$true.label,
                        alpha = 1, down.pct = 0.2, K = 20)
c.nmi <- plotSNFHeatComparison(all.data = snf.c$affinity.matrices,
                               truelabel = perturb.sim$true.label,
                               down.pct = 0.2)

```

```{r}
#Chapter 4 Figures -- normalized mutual information histograms -- should I add multiple kernel learning here?

NMI.values <- c(unlist(snf.b$nmi.values), unlist(snf.c$nmi.values))

Simulated.Data <- factor(c(rep("Noise Simulation", 3), rep("Boundary Misclassification", 3)),
                         levels = c("Noise Simulation", "Boundary Misclassification"))

Views <- factor(rep(c("View 1", "View 2", "Fused"), 2), levels = c("View 1", "View 2", "Fused"))
#levels(conditions) <- c("View 1", "View 2", "Fused")

nmi.data <- data.frame(Simulated.Data, Views, NMI.values)

ggplot(nmi.data, aes(fill = Views, y = NMI.values, x = Simulated.Data)) +
  geom_bar(aes(fill = Views), stat = "identity", position = "dodge")

```


```{r}
#Chapter 4 - figure 3 multiple kernel k means
#K means multiple kernel learning as implemented by Mehmet Gonen
mkkm.fxns <- "~/Documents/uva/master/the/utils/mkkm_fxns_sim.R"


mkkm.a <- runMKKMPipeline(Data1 = noise.sim$gaussian.noise,
                          Data2 = noise.sim$gamma.noise,
                          truelabel = noise.sim$true.label)

mmkm.a.nmi <- plotSNFHeatComparison(all.data = mkkm.a$kernel.matrices,
                                    truelabel = noise.sim$true.label,
                                    down.pct = 0.2)

mkkm.b <- runMKKMPipeline(Data1 = perturb.sim$perturbation.1,
                          Data2 = perturb.sim$perturbation.2,
                          truelabel = perturb.sim$true.label,
                          scale.factor = 1/32)

mmkm.b.nmi <- plotSNFHeatComparison(all.data = mkkm.b$kernel.matrices,
                                    truelabel = noise.sim$true.label,
                                    down.pct = 0.2)


```

```{r}
#NMI values for the multiple kernel k means experiment

#Chapter 4 Figures -- normalized mutual information histograms -- should I add multiple kernel learning here?

NMI.values <- c(unlist(mkkm.a$nmi.values), unlist(mkkm.b$nmi.values))

Simulated.Data <- factor(c(rep("Noise Simulation", 3), rep("Boundary Misclassification", 3)),
                         levels = c("Noise Simulation", "Boundary Misclassification"))

Views <- factor(rep(c("View 1", "View 2", "Fused"), 2), levels = c("View 1", "View 2", "Fused"))
#levels(conditions) <- c("View 1", "View 2", "Fused")

nmi.data <- data.frame(Simulated.Data, Views, NMI.values)

ggplot(nmi.data, aes(fill = Views, y = NMI.values, x = Simulated.Data)) +
  geom_bar(aes(fill = Views), stat = "identity", position = "dodge")

```


```{r}
#Chapter 4 unsupervised learning on real data....
#Run SNF pipeline on GBM data (also with breast, kidney, liver...) from paper
#Read in the Verhaaken Gene Sets
root.dir <- "~/Documents/gitRepos/master/data/GBM_genesets/"
gene.sets <- list()
gene.sets$classical <- read.table(paste0(root.dir, "geneset_classical.txt"), stringsAsFactors = FALSE)$V1
gene.sets$mesenchymal <- read.table(paste0(root.dir, "geneset_mesenchymal.txt"), stringsAsFactors = FALSE)$V1
gene.sets$neural <- read.table(paste0(root.dir, "geneset_neural.txt"), stringsAsFactors = FALSE)$V1
gene.sets$proneural <- read.table(paste0(root.dir, "geneset_proneural.txt"), stringsAsFactors = FALSE)$V1




snf.gbm.data <- processRealData(disease = "GBM", ks = TRUE, root.dir = "~/Documents/uva/master/data/SNF/")
#Manual parameters
C <- 4
K <- 50
alpha <- 0.3
num.pcs <- 15
snf.gbm <- runSNFPipelineRealData(object = snf.gbm.data,
                                  K = K, C = C, alpha = alpha,
                                  num.pcs = num.pcs)

#Make some silhouette plots - Single Data View predictions against single data view distances package these silhouette plots up!
plotSilhouetteSingle(snf.gbm, C)


#More silhouette Plots - Fused Data View predictions against single data view distances --- 

plotSilhouetteMulti(snf.gbm, C)

#Make a silhouette plot with the average value of each point's silhouette value for each data type
#aka plot average silhouette value for each point compare against the fused affinity matrix


#Plot affinity matrices 
plotSNFHeatComparison2(all.data = snf.gbm$affinity.matrices,
                      true.labels = snf.gbm$identity,
                      down.pct = 1)

#Take the predictions that ar made from the SNF pipeline and construct survival curves from the fused predictions

#Plotting the survival curves for all GBM patients, grouped by predicitions made from the Similarity Network Fusion approach vs groupings for single dataviews??
#Survival curves of individual view predictions and fused predictions
plotSurvivalCurves(disease = "GBM",
                   group.prediction = snf.gbm$identity$ge)
plotSurvivalCurves(disease = "GBM",
                   group.prediction = snf.gbm$identity$meth)
plotSurvivalCurves(disease = "GBM",
                   group.prediction = snf.gbm$identity$mirna)
plotSurvivalCurves(disease = "GBM", root.dir = "~/Documents/uva/master/data/SNF/",
                   group.prediction = snf.gbm$identity$W_fused)

#Plot the cluster layout using a pca based or tsne based coordinate system...
#Quality of other data views? -- these other data views look like absolute trash...
plotClustersDRSpace(fused.view = t(snf.gbm.data$data.views$ge),
                    group.prediction = snf.gbm$identity$W_fused,
                    reduction.use = "pca", main.title = "PCA reduction of Gene Expression Matrix")


plotClustersDRSpace(fused.view = t(snf.gbm.data$data.views$meth),
                    group.prediction = snf.gbm$identity$W_fused,
                    reduction.use = "pca", main.title = "PCA reduction of Meth Matrix")

plotClustersDRSpace(fused.view = t(snf.gbm.data$data.views$mirna),
                    group.prediction = snf.gbm$identity$W_fused,
                    reduction.use = "pca", main.title = "PCA reduction of miRNA Matrix")

plotClustersDRSpace(fused.view = snf.gbm$affinity.matrices$W_fused,
                    group.prediction = snf.gbm$identity$W_fused,
                    reduction.use = "pca", main.title = "PCA reduction of fused Matrix")

#Discriminative features using the Similarity Network Fusion cluster assignments

disc.features <- discriminativeFeatureSelection(snf.gbm.data$data.views, gene.sets$classical)

plotFeatureHeatMap(data.view = snf.gbm.data$data.views$ge,
                   features = names(disc.features$ge),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)
plotFeatureHeatMap(data.view = snf.gbm.data$data.views$meth,
                   features = names(disc.features$meth),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)
plotFeatureHeatMap(data.view = snf.gbm.data$data.views$mirna,
                   features = names(disc.features$mirna),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)

#Read in the Verhaaken Gene Sets
root.dir <- "~/Documents/gitRepos/master/data/GBM_genesets/"
gene.sets <- list()
gene.sets$classical <- read.table(paste0(root.dir, "geneset_classical.txt"), stringsAsFactors = FALSE)$V1
gene.sets$mesenchymal <- read.table(paste0(root.dir, "geneset_mesenchymal.txt"), stringsAsFactors = FALSE)$V1
gene.sets$neural <- read.table(paste0(root.dir, "geneset_neural.txt"), stringsAsFactors = FALSE)$V1
gene.sets$proneural <- read.table(paste0(root.dir, "geneset_proneural.txt"), stringsAsFactors = FALSE)$V1





######################################################################################################
#Do the same for MKKM pipeline @TODO

```


```{r}
#Analyze the GBM data using multiple kernel K-means


mkkm.gbm.data <- processRealData(disease = "GBM", ks = TRUE, root.dir = "~/Documents/uva/master/data/SNF/")

mkkm.gbm <- runMKKMPipelineRealData(object = mkkm.gbm.data, C = 4, num.pcs = 15)


#Make some silhouette plots - Single Data View predictions against single data view distances package these silhouette plots up!
plotSilhouetteSingle(mkkm.gbm, C)


#More silhouette Plots - Fused Data View predictions against single data view distances --- 

plotSilhouetteMulti(mkkm.gbm, C)

#Heatmap comparison
#Plot affinity matrices 
plotSNFHeatComparison2(all.data = mkkm.gbm$kernel.matrices,
                      true.labels = mkkm.gbm$identity,
                      down.pct = 1)


#Plotting the survival curves for all GBM patients, grouped by predicitions made from the Similarity Network Fusion approach vs groupings for single dataviews??
#Survival curves of individual view predictions and fused predictions
plotSurvivalCurves(disease = "GBM", root.dir = "~/Documents/uva/master/data/SNF/",
                   group.prediction = mkkm.gbm$identity$ge)
plotSurvivalCurves(disease = "GBM", root.dir = "~/Documents/uva/master/data/SNF/",
                   group.prediction = mkkm.gbm$identity$meth)
plotSurvivalCurves(disease = "GBM", root.dir = "~/Documents/uva/master/data/SNF/",
                   group.prediction = mkkm.gbm$identity$mirna)
plotSurvivalCurves(disease = "GBM", root.dir = "~/Documents/uva/master/data/SNF/",
                   group.prediction = mkkm.gbm$identity$mkkm.model)



#Plot the cluster layout using a pca based or tsne based coordinate system...
#Quality of other data views? -- these other data views look like absolute trash...
plotClustersDRSpace(fused.view = t(mkkm.gbm.data$data.views$ge),
                    group.prediction = mkkm.gbm$identity$mkkm.model,
                    reduction.use = "pca", main.title = "PCA reduction of Gene Expression Matrix")


plotClustersDRSpace(fused.view = t(mkkm.gbm.data$data.views$meth),
                    group.prediction = mkkm.gbm$identity$mkkm.model,
                    reduction.use = "pca", main.title = "PCA reduction of Meth Matrix")

plotClustersDRSpace(fused.view = t(mkkm.gbm.data$data.views$mirna),
                    group.prediction = mkkm.gbm$identity$mkkm.model,
                    reduction.use = "pca", main.title = "PCA reduction of miRNA Matrix")

plotClustersDRSpace(fused.view = mkkm.gbm$kernel.matrices$K_fused,
                    group.prediction = mkkm.gbm$identity$mkkm.model,
                    reduction.use = "pca", main.title = "PCA reduction of fused Matrix")
####
#Discriminative Feature heat map -- change to mkkm instead of results found from SNF
disc.features <- discriminativeFeatureSelection(snf.gbm.data$data.views, ident = snf.gbm$identity$W_fused)

plotFeatureHeatMap(data.view = snf.gbm.data$data.views$ge,
                   features = names(disc.features$ge),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)
plotFeatureHeatMap(data.view = snf.gbm.data$data.views$meth,
                   features = names(disc.features$meth),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)
plotFeatureHeatMap(data.view = snf.gbm.data$data.views$mirna,
                   features = names(disc.features$mirna),
                   ident = snf.gbm$identity$W_fused,
                   scale = "col", C = 4)


```
